# Generated by Django 4.2.7 on 2023-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarListing',
        ),
    ]
